name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          latexmk_use_xelatex: true
      - uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: main.pdf
      - run: echo ::set-output name=REPONAME::${GITHUB_REPOSITORY#*/}
        # https://stackoverflow.com/a/61560798
      - run: echo ::set-output name=TAG::${GITHUB_REF#refs/*/}
        # https://stackoverflow.com/a/58178121
      - name: Rename for release
        if: startsWith(github.ref, 'refs/tags/')
        env:
          RELEASE: ${{ steps.vars.outputs.TAG}}
          REPO: ${{ steps.vars.outputs.REPONAME}}
        run: |
          cp "main.pdf" "$REPO-$RELEASE.pdf"        
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          RELEASE: ${{ steps.vars.outputs.TAG}}
          REPO: ${{ steps.vars.outputs.REPONAME}}
        with:
          files: |
            $REPO-$RELEASE.pdf        